spring:
  profiles:
    active: dev
  application:
    name: spring-boot-api
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootapi
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

api:
  base-path: /api/v1
  hello-path: /hello
  counterparty-risk-profiles-path: /counterparty-risk-profiles
  transferencias-path: /transferencias
  cryptocurrencies-path: /cryptocurrencies
  version:
    header-name: X-API-Version
    default-version: "1"
    supported: "1"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
